import random
import discord
from discord import app_commands
from discord.ext import commands

# List of random quotes
QUOTES = [
    "Accept everything just the way it is.",
    "Do not seek pleasure for its own sake.",
    "Do not, under any circumstances, depend on a partial feeling.",
    "Think lightly of yourself and deeply of the world.",
    "Be detached from desire your whole life long.",
    "Do not regret what you have done.",
    "Never be jealous.",
    "Never let yourself be saddened by a separation.",
    "Resentment and complaint are appropriate neither for oneself nor others.",
    "Do not let yourself be guided by the feeling of lust or love.",
    "In all things have no preferences.",
    "Be indifferent to where you live.",
    "Do not pursue the taste of good food.",
    "Do not hold on to possessions you no longer need.",
    "Do not act following customary beliefs.",
    "Do not collect weapons or practice with weapons beyond what is useful.",
    "Do not fear death.",
    "Do not seek to possess either goods or fiefs for your old age.",
    "Respect Buddha and the gods without counting on their help.",
    "You may abandon your own body but you must preserve your honor.",
    "Never stray from the Way.",
    "The ultimate aim of martial arts is not having to use them.",
    "Do nothing that is of no use.",
    "You must understand that there is more than one path to the top of the mountain.",
    "Perceive that which cannot be seen with the eye.",
    "You can only fight the way you practice.",
    "In battle, if you make your opponent flinch, you have already won.",
    "Today is victory over yourself of yesterday; tomorrow is your victory over lesser men.",
    "It is difficult to understand the universe if you only study one planet.",
    "All men are the same except for their belief in their own selves.",
    "From one thing, know ten thousand things.",
    "If you wish to control others you must first control yourself.",
    "Truth is not what you want it to be; it is what it is.",
    "It may seem difficult at first, but everything is difficult at first.",
    "Step by step walk the thousand-mile road.",
    "When you decide to attack, keep calm and dash in quickly.",
    "Your spirit must be settled, yet your body should not relax.",
    "A warrior must constantly be mindful and diligent in his training.",
    "Mastery is achieved through relentless practice.",
    "The true value of a warrior lies in his ability to remain calm in chaos.",
    "Discipline and determination pave the path to victory.",
    "Every defeat is a lesson that brings you closer to success.",
    "Overcome your fears, for they are the true enemy.",
    "A clear mind sees opportunities where others see obstacles.",
    "Strength comes from within; cultivate your inner power.",
    "Consistency in practice transforms potential into excellence.",
    "Every challenge is a stepping stone to greatness.",
    "In the midst of conflict, clarity and focus are your greatest allies.",
    "Victory is born from perseverance in the face of adversity.",
    "The art of war begins with mastering oneself.",
    "Success is the result of continuous effort and self-improvement.",
    "Embrace challenges as opportunities to grow stronger.",
    "In adversity, find the strength to persist and overcome.",
    "A true warrior adapts to every situation with grace and resolve.",
    "Let every battle refine you, not define you.",
    "Harness your inner strength and let it guide your actions.",
    "Every moment is a chance to rewrite your destiny.",
    "Do not be swayed by the opinions of others; follow your own path.",
    "Embody courage, for it is the foundation of all success.",
    "In the quiet moments, you forge the strength to face the storm.",
    "True power lies in the mastery of one's own mind.",
    "Cultivate discipline, and your spirit will soar.",
    "Every action you take is a reflection of your inner resolve.",
    "The journey to greatness is paved with unwavering determination.",
    "Let your perseverance be the armor that shields you from defeat.",
    "Greatness is achieved by those who never give up.",
    "Every step forward, no matter how small, is progress.",
    "Focus your energy on what you can control, and let go of the rest.",
    "In every setback lies the seed of an even greater comeback.",
    "Rise above limitations and embrace the power of self-belief.",
    "The path to excellence is forged through consistent, mindful practice.",
    "Let your actions speak louder than your words.",
    "A steadfast heart conquers even the fiercest challenges.",
    "Embrace the journey of self-mastery and let it illuminate your path.",
    "In the face of fear, let determination be your guide.",
    "Every moment is a battle; fight it with honor and integrity.",
    "The true test of a warrior is not in his victories, but in his ability to learn from defeat.",
    "Dedicate yourself to constant improvement, and success will follow.",
    "Let every challenge strengthen your resolve and sharpen your skills.",
    "Your potential is limitless when you harness the power of your will.",
    "Success is not measured by the absence of failure, but by the courage to continue.",
    "Every struggle you face is an opportunity to grow wiser and stronger.",
    "The mind of a warrior is both calm and relentless.",
    "Channel your energy into every action, and let nothing hold you back.",
    "Embrace the discipline of the warrior, and you will conquer all obstacles.",
    "In the pursuit of excellence, every small effort counts.",
    "Let resilience be the bridge between ambition and achievement.",
    "A clear and focused mind transforms challenges into victories.",
    "Strength is built through adversity and the courage to persevere.",
    "The spirit of a warrior thrives on challenges and constant growth.",
    "Keep your mind sharp, your body ready, and your spirit unyielding.",
    "Great achievements come to those who never lose sight of their goals.",
    "Harness the power of perseverance to break through any barrier.",
    "Let determination be the driving force behind every step you take.",
    "Every day is an opportunity to become a better version of yourself.",
    "Cultivate a warrior's mindset and watch your life transform.",
    "Your journey to greatness begins with a single step of courage.",
    "Success is forged in the fires of discipline, resilience, and hard work.",
    "Let the lessons of the past inspire your actions in the present.",
    "Embrace the way of the warrior and let it guide you to triumph."
]

async def setup(bot: commands.Bot):
    @bot.tree.command(name="quotes", description="Get a random motivational quote")
    async def quotes_command(interaction: discord.Interaction):

        random_quote = random.choice(QUOTES)
        await interaction.response.send_message(random_quote)